### PR TITLE
Add go1.18 support; set go1.18 in Dockerfile

### PR DESCRIPTION
**Pull request by gpassini**

### CODE REVIEW

**Review by dragonsinth — APPROVED** [review]
This LGTM by inspection, but IDK why CI didn't run?

**Comment by dragonsinth** [comment]
CI looks green... https://app.circleci.com/pipelines/github/fullstorydev/grpcui?branch=go118

**Comment by gpassini** [comment]
> This LGTM by inspection, but IDK why CI didn't run?

I don't know why the CI tests reporting is stuck, but it seems to be the case only on GitHub's side, and it's the same for all currently open PRs.

Given the checks are green, is there anything else I should check before merging this?

**Comment by dragonsinth** [comment]
Merge away

**Comment by gpassini** [comment]
> Merge away

Actually, I'm blocked by the missing status reports :(

**Pull request merged**
