### PR TITLE
Include protobuf comments in web form

### PR DESCRIPTION
**Pull request by n0v1**
This PR implements the display of explanatory comments from the protobuf file in the web form (#50).

In the current state comments of methods (rpcs) are displayed and comments attached to single fields. This can be easily extended to other comments (e.g. for services, message types, ...). The main question is where and how to display information from the comments. For method descriptions I opted for displaying them directly below the method select, field comments will be displayed when hovering an icon to not overload the form.

This feature is hidden behind boolean option `comments`. Use command line flag `-comments` (or `-comments=true`) to activate it.

Tested with plain proto and descriptor set compiled with `–include_source_info`.

Please review, test, discuss.

Example:

Method comments in protobuf file:
image

Field comments in protobuf file:
image

Result:
image

### CODE REVIEW

**Comment by n0v1** [comment]
@jhump when do you think you'll find some time to look at this?

**Comment by n0v1** [comment]
Thanks for the detailed write-up. I'll adjust/move the text as suggested and see how it looks. It may take some days until I find some free time to work on this.

**Comment by n0v1** [comment]
@jhump I just added a commit that moves the method comment to the right of the dropdowns and keeps newlines.

**Comment by jhump** [comment]
@n0v1, check out #166. Closing this since that PR handles this and more, by also showing options and making it showable/collapsible at runtime (instead of needing command-line flag to toggle it on).

**Comment by jhump** [comment]
> @jhump I just added a commit that moves the method comment to the right of the dropdowns and keeps newlines.

Hey, I am sorry that we seem to have duplicated some effort. I was also working on this over the weekend and didn't realize you would also be revisiting my last comments from last month. I do appreciate your PR; I did use it as the basis for #166 when I started pushing further in the direction I had stated above.

**Comment by n0v1** [comment]
No worries. I'm glad that this feature has landed now and is even more powerful than what I cobbled together. Thanks you for working on this 👍

**Pull request closed without merging**
